# Code to prepare datasets for analysis

In [13]:
import pandas as pd
import numpy as np
import seaborn as sns

from pybaseball import batting_stats
from pybaseball import statcast_batter_expected_stats, statcast_batter_exitvelo_barrels

In [8]:
qualifying_threshold = 502

fg_bat_data = batting_stats(2015, 2024, qual = qualifying_threshold)
fg_bat_data

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
0,15640,2024,Aaron Judge,NYY,32,158,559,704,180,85,...,117.5,238,0.609,391,0.146,0.267,NaN,NaN,NaN,11.3
2,15640,2022,Aaron Judge,NYY,30,157,570,696,177,87,...,118.4,246,0.609,404,0.169,0.287,NaN,NaN,NaN,11.4
38,25764,2024,Bobby Witt Jr.,KCR,24,161,636,709,211,123,...,116.9,259,0.481,538,0.138,0.236,NaN,NaN,NaN,10.0
3,13611,2018,Mookie Betts,BOS,25,136,520,614,180,96,...,110.6,217,0.500,434,0.220,0.270,NaN,NaN,NaN,10.4
4,10155,2018,Mike Trout,LAA,26,140,471,608,147,80,...,118.0,162,0.460,352,0.201,0.261,NaN,NaN,NaN,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1064,10815,2023,Jurickson Profar,- - -,30,125,459,521,111,73,...,108.8,119,0.317,375,0.151,0.236,NaN,NaN,NaN,-1.8
1130,6876,2017,Mark Trumbo,BAL,31,146,559,603,131,86,...,118.5,154,0.375,411,0.154,0.291,NaN,NaN,NaN,-1.8
1191,393,2018,Victor Martinez,DET,39,133,467,508,117,87,...,107.6,129,0.304,425,0.148,0.212,NaN,NaN,NaN,-1.7
1170,1177,2017,Albert Pujols,LAA,37,149,593,636,143,103,...,112.2,197,0.391,504,0.180,0.268,NaN,NaN,NaN,-1.9
1232,9272,2018,Chris Davis,BAL,32,128,470,522,79,51,...,111.8,113,0.401,282,0.174,0.316,NaN,NaN,NaN,-2.6

In [7]:
fg_bat_data.to_csv('../data/fangraphs_player_data.csv', index = False)

In [6]:
exp_bat_data = pd.DataFrame()

for year in range(2015, 2025):
    exp_bat_yearly = statcast_batter_expected_stats(year)
    exp_bat_yearly = exp_bat_yearly[exp_bat_yearly['pa'] > qualifying_threshold]

    exp_bat_data = pd.concat([exp_bat_data, exp_bat_yearly], ignore_index=True)

exp_bat_data

,"last_name, first_name",player_id,year,pa,bip,ba,est_ba,est_ba_minus_ba_diff,slg,est_slg,est_slg_minus_slg_diff,woba,est_woba,est_woba_minus_woba_diff
0,"Machado, Manny",592518,2015,713,528,0.286,0.262,0.024,0.502,0.447,0.055,0.370,0.345,0.025
1,"Donaldson, Josh",518626,2015,711,499,0.297,0.279,0.018,0.568,0.545,0.023,0.398,0.390,0.008
2,"Dozier, Brian",572821,2015,704,488,0.236,0.220,0.016,0.444,0.380,0.064,0.323,0.299,0.024
3,"Rizzo, Anthony",519203,2015,701,488,0.278,0.275,0.003,0.512,0.496,0.016,0.384,0.383,0.001
4,"Votto, Joey",458015,2015,695,412,0.314,0.289,0.025,0.541,0.541,0.000,0.427,0.422,0.005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,"Varsho, Daulton",662139,2024,513,324,0.214,0.186,0.028,0.407,0.316,0.091,0.304,0.261,0.043
1225,"Meyers, Jake",676694,2024,513,351,0.219,0.235,-0.016,0.360,0.382,-0.022,0.285,0.304,-0.019
1226,"Ortiz, Joey",687401,2024,511,346,0.239,0.234,0.005,0.398,0.343,0.055,0.319,0.305,0.014
1227,"Winker, Jesse",608385,2024,508,329,0.253,0.245,0.008,0.405,0.384,0.021,0.338,0.329,0.009
1228,"Mountcastle, Ryan",663624,2024,507,365,0.271,0.272,-0.001,0.425,0.445,-0.020,0.316,0.332,-0.016

In [10]:
exp_bat_data.to_csv('../data/statcast_expected_batting_data', index = False)

In [39]:
statcast_batter_exitvelo_barrels(2015)

,"last_name, first_name",player_id,attempts,avg_hit_angle,anglesweetspotpercent,max_hit_speed,avg_hit_speed,ev50,fbld,gb,max_distance,avg_distance,avg_hr_distance,ev95plus,ev95percent,barrels,brl_percent,brl_pa
0,"Altuve, Jose",514888,580,11.2,31.2,106.5,86.1,96.2,90.2,84.0,410,159,386.0,166,28.6,18,3.1,2.6
1,"Cabrera, Melky",466320,553,9.7,30.9,111.0,89.6,99.2,91.2,90.4,455,163,399.0,200,36.2,13,2.4,1.9
2,"Escobar, Alcides",444876,553,9.6,30.4,106.2,84.6,93.2,86.4,84.2,407,154,395.0,91,16.5,5,0.9,0.8
3,"Kinsler, Ian",435079,549,17.7,36.6,105.5,86.1,95.2,88.6,84.4,407,189,378.0,146,26.6,15,2.7,2.2
4,"Aybar, Erick",430947,536,6.6,31.2,108.1,85.7,94.6,87.8,84.6,409,144,389.0,104,19.4,5,0.9,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,"Souza Jr., Steven",519306,231,13.9,27.7,113.2,88.9,101.5,94.4,86.0,446,167,404.0,90,39.0,22,9.5,5.2
246,"Flowers, Tyler",452095,230,11.8,27.8,114.2,90.4,101.4,91.7,91.4,448,156,411.0,91,39.6,11,4.8,3.0
247,"Zunino, Mike",572287,228,21.8,28.9,110.6,88.8,99.2,93.7,83.7,452,200,413.0,77,33.8,20,8.8,5.2
248,"Castro, Jason",488771,225,15.8,35.6,109.5,88.5,97.8,91.5,85.1,429,183,373.0,69,30.7,13,5.8,3.5
249,"Grichuk, Randal",545341,214,16.3,34.1,112.0,92.2,102.9,98.0,88.1,438,203,409.0,99,46.3,36,16.8,10.3

In [40]:
len(statcast_batter_exitvelo_barrels(2015)['last_name, first_name'].unique())

250

In [41]:
exit_velo_barrels_data = pd.DataFrame()

for year in range(2015, 2025):
    exit_velo_barrels_data_yearly = statcast_batter_exitvelo_barrels(year)
    exit_velo_barrels_data_yearly['year'] = year
    exit_velo_barrels_data = pd.concat([exit_velo_barrels_data, exit_velo_barrels_data_yearly], ignore_index=True)

exit_velo_barrels_data

,"last_name, first_name",player_id,attempts,avg_hit_angle,anglesweetspotpercent,max_hit_speed,avg_hit_speed,ev50,fbld,gb,max_distance,avg_distance,avg_hr_distance,ev95plus,ev95percent,barrels,brl_percent,brl_pa,year
0,"Altuve, Jose",514888,580,11.2,31.2,106.5,86.1,96.2,90.2,84.0,410,159,386.0,166,28.6,18,3.1,2.6,2015
1,"Cabrera, Melky",466320,553,9.7,30.9,111.0,89.6,99.2,91.2,90.4,455,163,399.0,200,36.2,13,2.4,1.9,2015
2,"Escobar, Alcides",444876,553,9.6,30.4,106.2,84.6,93.2,86.4,84.2,407,154,395.0,91,16.5,5,0.9,0.8,2015
3,"Kinsler, Ian",435079,549,17.7,36.6,105.5,86.1,95.2,88.6,84.4,407,189,378.0,146,26.6,15,2.7,2.2,2015
4,"Aybar, Erick",430947,536,6.6,31.2,108.1,85.7,94.6,87.8,84.6,409,144,389.0,104,19.4,5,0.9,0.8,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2492,"Gorman, Nolan",669357,216,20.3,40.3,111.0,88.5,100.7,93.7,80.2,436,201,399.0,83,38.6,36,16.7,9.0,2024
2493,"Fitzgerald, Tyler",666149,207,20.2,38.6,107.3,87.7,97.6,90.6,83.6,434,187,397.0,66,31.9,17,8.2,5.0,2024
2494,"Contreras, Willson",575929,205,14.2,32.7,115.3,91.6,103.7,95.3,90.3,445,168,410.0,96,46.8,23,11.2,6.4,2024
2495,"Benson, Will",666181,192,18.2,36.5,110.7,89.4,99.8,94.0,83.2,439,187,397.0,77,40.1,22,11.5,5.7,2024
2496,"Bauers, Jake",641343,184,22.6,38.6,110.1,89.4,100.0,92.7,84.3,444,198,401.0,79,42.9,19,10.3,5.5,2024

In [42]:
exit_velo_barrels_data.to_csv('../data/statcast_exvelo_barr_data', index = False)