# Playground
- A place to put random bits of code and see how they work.

In [11]:
import pandas as pd
import numpy as np

In [1]:
from pybaseball import statcast_batter
from pybaseball import playerid_lookup

shohei_id = playerid_lookup('ohtani', 'shohei')

Gathering player lookup table. This may take a moment.

In [2]:
shohei_id

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,ohtani,shohei,660271,ohtas001,ohtansh01,19755,2018.0,2024.0

In [3]:
statcast_batter('2024-04-01', '2024-09-10', player_id = 660271)

Gathering Player Data

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle
0,ST,2024-09-10,82.6,2.90,5.30,"Ohtani, Shohei",660271,684007,field_out,hit_into_play,...,3,2,6.0,1,6.0,1,3.46,-1.27,-1.27,35.2
1,ST,2024-09-10,83.7,2.99,5.18,"Ohtani, Shohei",660271,684007,NaN,swinging_strike,...,3,2,6.0,1,6.0,1,3.26,-0.99,-0.99,36.0
2,ST,2024-09-10,82.1,3.03,5.17,"Ohtani, Shohei",660271,684007,grounded_into_double_play,hit_into_play,...,2,1,6.0,1,6.0,1,3.01,-0.41,-0.41,34.1
3,FS,2024-09-10,83.2,3.02,5.31,"Ohtani, Shohei",660271,684007,NaN,ball,...,2,1,6.0,1,6.0,1,2.85,0.25,0.25,33.9
4,ST,2024-09-10,82.6,3.06,5.20,"Ohtani, Shohei",660271,684007,NaN,blocked_ball,...,2,1,6.0,1,6.0,1,3.31,-1.01,-1.01,34.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2430,FS,2024-04-01,90.7,-1.50,5.97,"Ohtani, Shohei",660271,676775,NaN,ball,...,1,0,NaN,1,5.0,1,2.62,1.41,-1.41,39.8
2431,FC,2024-04-01,87.5,-1.88,6.11,"Ohtani, Shohei",660271,687014,NaN,foul,...,1,3,NaN,1,5.0,1,2.62,-0.31,0.31,52.1
2432,FF,2024-04-01,94.0,-1.76,6.12,"Ohtani, Shohei",660271,687014,NaN,called_strike,...,1,3,NaN,1,5.0,1,1.39,0.54,-0.54,50.8
2433,FF,2024-04-01,97.8,-1.24,6.20,"Ohtani, Shohei",660271,676775,NaN,swinging_strike,...,1,0,NaN,1,5.0,1,1.01,0.74,-0.74,41.3
2434,FC,2024-04-01,84.9,-1.73,6.10,"Ohtani, Shohei",660271,687014,NaN,ball,...,1,3,NaN,1,5.0,1,2.94,-0.19,0.19,53.6

In [7]:
from pybaseball import batting_stats

bat_stat = batting_stats(2021, 2024, qual = 502, split_seasons = True)
bat_stat

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
0,15640,2024,Aaron Judge,NYY,32,158,559,704,180,85,...,117.5,238,0.609,391,0.146,0.267,NaN,NaN,NaN,11.3
1,15640,2022,Aaron Judge,NYY,30,157,570,696,177,87,...,118.4,246,0.609,404,0.169,0.287,NaN,NaN,NaN,11.4
15,25764,2024,Bobby Witt Jr.,KCR,24,161,636,709,211,123,...,116.9,259,0.481,538,0.138,0.236,NaN,NaN,NaN,10.0
4,19755,2024,Shohei Ohtani,LAD,29,159,636,731,197,98,...,119.2,287,0.595,482,0.144,0.269,NaN,NaN,NaN,9.0
5,18401,2023,Ronald Acuna Jr.,ATL,25,159,643,735,217,137,...,121.2,310,0.552,562,0.137,0.214,NaN,NaN,NaN,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,17982,2024,Ty France,- - -,29,140,479,535,112,75,...,111.1,147,0.397,370,0.128,0.237,NaN,NaN,NaN,-0.8
510,21897,2024,Christopher Morel,- - -,25,152,535,611,105,70,...,111.4,154,0.404,381,0.149,0.298,NaN,NaN,NaN,-0.9
507,10472,2023,Enrique Hernandez,- - -,31,140,465,508,110,76,...,109.2,125,0.334,374,0.177,0.279,NaN,NaN,NaN,-1.3
505,19600,2024,Bryan De La Cruz,- - -,27,149,584,622,136,90,...,110.5,172,0.410,420,0.135,0.280,NaN,NaN,NaN,-1.1
453,10815,2023,Jurickson Profar,- - -,30,125,459,521,111,73,...,108.8,119,0.317,375,0.151,0.236,NaN,NaN,NaN,-1.8

In [14]:
for i in range(len(bat_stat.columns)):
    print(bat_stat.columns[i])

IDfg
Season
Name
Team
Age
G
AB
PA
H
1B
2B
3B
HR
R
RBI
BB
IBB
SO
HBP
SF
SH
GDP
SB
CS
AVG
GB
FB
LD
IFFB
Pitches
Balls
Strikes
IFH
BU
BUH
BB%
K%
BB/K
OBP
SLG
OPS
ISO
BABIP
GB/FB
LD%
GB%
FB%
IFFB%
HR/FB
IFH%
BUH%
wOBA
wRAA
wRC
Bat
Fld
Rep
Pos
RAR
WAR
Dol
Spd
wRC+
WPA
-WPA
+WPA
RE24
REW
pLI
phLI
PH
WPA/LI
Clutch
FB% (Pitch)
FBv
SL%
SLv
CT%
CTv
CB%
CBv
CH%
CHv
SF%
SFv
KN%
KNv
XX%
PO%
wFB
wSL
wCT
wCB
wCH
wSF
wKN
wFB/C
wSL/C
wCT/C
wCB/C
wCH/C
wSF/C
wKN/C
O-Swing%
Z-Swing%
Swing%
O-Contact%
Z-Contact%
Contact%
Zone%
F-Strike%
SwStr%
BsR
FA% (sc)
FT% (sc)
FC% (sc)
FS% (sc)
FO% (sc)
SI% (sc)
SL% (sc)
CU% (sc)
KC% (sc)
EP% (sc)
CH% (sc)
SC% (sc)
KN% (sc)
UN% (sc)
vFA (sc)
vFT (sc)
vFC (sc)
vFS (sc)
vFO (sc)
vSI (sc)
vSL (sc)
vCU (sc)
vKC (sc)
vEP (sc)
vCH (sc)
vSC (sc)
vKN (sc)
FA-X (sc)
FT-X (sc)
FC-X (sc)
FS-X (sc)
FO-X (sc)
SI-X (sc)
SL-X (sc)
CU-X (sc)
KC-X (sc)
EP-X (sc)
CH-X (sc)
SC-X (sc)
KN-X (sc)
FA-Z (sc)
FT-Z (sc)
FC-Z (sc)
FS-Z (sc)
FO-Z (sc)
SI-Z (sc)
SL-Z (sc)
CU-Z (sc)
KC-Z (sc)
EP-Z (sc)
CH-Z (sc)
SC-Z (sc)
KN-Z (sc)
wFA (sc)
wFT (sc)
wFC (sc)
wFS (sc)
wFO (sc)
wSI (sc)
wSL (sc)
wCU (sc)
wKC (sc)
wEP (sc)
wCH (sc)
wSC (sc)
wKN (sc)
wFA/C (sc)
wFT/C (sc)
wFC/C (sc)
wFS/C (sc)
wFO/C (sc)
wSI/C (sc)
wSL/C (sc)
wCU/C (sc)
wKC/C (sc)
wEP/C (sc)
wCH/C (sc)
wSC/C (sc)
wKN/C (sc)
O-Swing% (sc)
Z-Swing% (sc)
Swing% (sc)
O-Contact% (sc)
Z-Contact% (sc)
Contact% (sc)
Zone% (sc)
Pace
Def
wSB
UBR
Age Rng
Off
Lg
wGDP
Pull%
Cent%
Oppo%
Soft%
Med%
Hard%
TTO%
CH% (pi)
CS% (pi)
CU% (pi)
FA% (pi)
FC% (pi)
FS% (pi)
KN% (pi)
SB% (pi)
SI% (pi)
SL% (pi)
XX% (pi)
vCH (pi)
vCS (pi)
vCU (pi)
vFA (pi)
vFC (pi)
vFS (pi)
vKN (pi)
vSB (pi)
vSI (pi)
vSL (pi)
vXX (pi)
CH-X (pi)
CS-X (pi)
CU-X (pi)
FA-X (pi)
FC-X (pi)
FS-X (pi)
KN-X (pi)
SB-X (pi)
SI-X (pi)
SL-X (pi)
XX-X (pi)
CH-Z (pi)
CS-Z (pi)
CU-Z (pi)
FA-Z (pi)
FC-Z (pi)
FS-Z (pi)
KN-Z (pi)
SB-Z (pi)
SI-Z (pi)
SL-Z (pi)
XX-Z (pi)
wCH (pi)
wCS (pi)
wCU (pi)
wFA (pi)
wFC (pi)
wFS (pi)
wKN (pi)
wSB (pi)
wSI (pi)
wSL (pi)
wXX (pi)
wCH/C (pi)
wCS/C (pi)
wCU/C (pi)
wFA/C (pi)
wFC/C (pi)
wFS/C (pi)
wKN/C (pi)
wSB/C (pi)
wSI/C (pi)
wSL/C (pi)
wXX/C (pi)
O-Swing% (pi)
Z-Swing% (pi)
Swing% (pi)
O-Contact% (pi)
Z-Contact% (pi)
Contact% (pi)
Zone% (pi)
Pace (pi)
FRM
AVG+
BB%+
K%+
OBP+
SLG+
ISO+
BABIP+
LD+%
GB%+
FB%+
HR/FB%+
Pull%+
Cent%+
Oppo%+
Soft%+
Med%+
Hard%+
EV
LA
Barrels
Barrel%
maxEV
HardHit
HardHit%
Events
CStr%
CSW%
xBA
xSLG
xwOBA
L-WAR

In [16]:
batting_stats(2000, 2024)

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
0,1109,2002,Barry Bonds,SFG,37,143,403,612,149,70,...,NaN,NaN,NaN,0,0.127,0.191,NaN,NaN,NaN,12.7
2,1109,2001,Barry Bonds,SFG,36,153,476,664,156,49,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,12.5
1,1109,2004,Barry Bonds,SFG,39,147,373,617,135,60,...,NaN,NaN,NaN,0,0.124,0.164,NaN,NaN,NaN,11.9
7,15640,2024,Aaron Judge,NYY,32,158,559,704,180,85,...,117.5,238.0,0.609,391,0.146,0.267,NaN,NaN,NaN,11.3
18,15640,2022,Aaron Judge,NYY,30,157,570,696,177,87,...,118.4,246.0,0.609,404,0.169,0.287,NaN,NaN,NaN,11.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3262,1213,2009,Aubrey Huff,- - -,32,150,536,597,129,83,...,NaN,0.0,NaN,0,0.169,0.246,NaN,NaN,NaN,-2.1
3196,857,2005,Bernie Williams,NYY,36,141,485,546,121,89,...,NaN,NaN,NaN,0,0.183,0.255,NaN,NaN,NaN,-2.3
3622,8585,2009,Yuniesky Betancourt,- - -,27,134,470,508,115,83,...,NaN,0.0,NaN,0,0.181,0.232,NaN,NaN,NaN,-2.4
3681,9272,2018,Chris Davis,BAL,32,128,470,522,79,51,...,111.8,113.0,0.401,282,0.174,0.316,NaN,NaN,NaN,-2.6
3678,620,2002,Neifi Perez,KCR,29,145,554,585,131,104,...,NaN,NaN,NaN,0,0.130,0.187,NaN,NaN,NaN,-2.9

In [14]:
from pybaseball import statcast_batter_expected_stats, statcast_batter_percentile_ranks

#gets expected batting statistics from baseball savant
exp_stat = statcast_batter_expected_stats(2024)
exp_stat[exp_stat['pa'] > 502]

,"last_name, first_name",player_id,year,pa,bip,ba,est_ba,est_ba_minus_ba_diff,slg,est_slg,est_slg_minus_slg_diff,woba,est_woba,est_woba_minus_woba_diff
0,"Duran, Jarren",680776,2024,735,515,0.285,0.275,0.010,0.492,0.453,0.039,0.357,0.342,0.015
1,"Ohtani, Shohei",660271,2024,731,479,0.310,0.314,-0.004,0.646,0.660,-0.014,0.431,0.442,-0.011
2,"Henderson, Gunnar",683002,2024,719,475,0.281,0.283,-0.002,0.529,0.492,0.037,0.381,0.374,0.007
3,"Semien, Marcus",543760,2024,718,546,0.237,0.251,-0.014,0.391,0.391,0.000,0.306,0.313,-0.007
4,"Soto, Juan",665742,2024,713,461,0.288,0.316,-0.028,0.569,0.646,-0.077,0.421,0.462,-0.041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,"Varsho, Daulton",662139,2024,513,324,0.214,0.186,0.028,0.407,0.316,0.091,0.304,0.261,0.043
125,"Meyers, Jake",676694,2024,513,351,0.219,0.235,-0.016,0.360,0.382,-0.022,0.285,0.304,-0.019
126,"Ortiz, Joey",687401,2024,511,346,0.239,0.234,0.005,0.398,0.343,0.055,0.319,0.305,0.014
127,"Winker, Jesse",608385,2024,508,329,0.253,0.245,0.008,0.405,0.384,0.021,0.338,0.329,0.009
128,"Mountcastle, Ryan",663624,2024,507,365,0.271,0.272,-0.001,0.425,0.445,-0.020,0.316,0.332,-0.016

In [16]:
statcast_batter_percentile_ranks(2024)

,player_name,player_id,year,xwoba,xba,xslg,xiso,xobp,brl,brl_percent,...,k_percent,bb_percent,whiff_percent,chase_percent,arm_strength,sprint_speed,oaa,bat_speed,squared_up_rate,swing_length
0,"McCann, Kyle",668832,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN
1,"Outman, James",681546,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,81.0,87,NaN,NaN,NaN,NaN
2,"Trout, Mike",545361,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,44.0,90,NaN,NaN,NaN,NaN
3,"Encarnacion-Strand, Christian",687952,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,50,NaN,NaN,NaN,NaN
4,"Moreno, Gabriel",672515,2024,60.0,62.0,38.0,29.0,86.0,20.0,36.0,...,91.0,92.0,84.0,91.0,NaN,44,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,"Bichette, Bo",666182,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,37.0,49,70.0,NaN,NaN,NaN
602,"Moore, Dylan",664238,2024,26.0,3.0,6.0,22.0,59.0,37.0,58.0,...,15.0,94.0,47.0,99.0,11.0,68,66.0,68.0,11.0,72.0
603,"Robert Jr., Luis",673357,2024,6.0,6.0,25.0,47.0,3.0,45.0,66.0,...,2.0,28.0,2.0,10.0,54.0,88,75.0,84.0,4.0,13.0
604,"O'Neill, Tyler",641933,2024,76.0,8.0,90.0,97.0,44.0,81.0,98.0,...,2.0,87.0,5.0,65.0,82.0,55,18.0,90.0,3.0,18.0
605,"Toglia, Michael",669911,2024,90.0,42.0,93.0,96.0,75.0,81.0,98.0,...,4.0,92.0,3.0,57.0,4.0,51,12.0,70.0,16.0,29.0

In [15]:
from pybaseball import statcast_batter_exitvelo_barrels

data = statcast_batter_exitvelo_barrels(2024)
data

,"last_name, first_name",player_id,attempts,avg_hit_angle,anglesweetspotpercent,max_hit_speed,avg_hit_speed,ev50,fbld,gb,max_distance,avg_distance,avg_hr_distance,ev95plus,ev95percent,barrels,brl_percent,brl_pa
0,"Arraez, Luis",650333,611,13.7,40.9,108.4,86.3,94.8,89.3,83.9,401,164,379,145,23.7,10,1.6,1.5
1,"Semien, Marcus",543760,546,17.0,33.0,112.1,87.4,97.8,91.1,84.4,422,173,387,192,35.2,36,6.6,5.0
2,"Ramírez, José",608070,544,19.6,34.0,116.6,89.2,99.6,93.0,87.5,451,184,389,216,39.7,47,8.6,6.9
3,"Witt Jr., Bobby",677951,538,15.1,35.7,116.9,92.7,104.0,95.3,91.1,468,187,411,260,48.3,77,14.3,10.9
4,"Guerrero Jr., Vladimir",665489,524,7.4,35.1,117.6,93.8,105.7,97.1,91.6,471,162,412,287,54.9,72,13.7,10.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,"Gorman, Nolan",669357,216,20.3,40.3,111.0,88.5,100.7,93.7,80.2,436,201,399,83,38.6,36,16.7,9.0
248,"Fitzgerald, Tyler",666149,207,20.2,38.6,107.3,87.7,97.6,90.6,83.6,434,187,397,66,31.9,17,8.2,5.0
249,"Contreras, Willson",575929,205,14.2,32.7,115.3,91.6,103.7,95.3,90.3,445,168,410,96,46.8,23,11.2,6.4
250,"Benson, Will",666181,192,18.2,36.5,110.7,89.4,99.8,94.0,83.2,439,187,397,77,40.1,22,11.5,5.7
251,"Bauers, Jake",641343,184,22.6,38.6,110.1,89.4,100.0,92.7,84.3,444,198,401,79,42.9,19,10.3,5.5

In [18]:
from pybaseball import playerid_reverse_lookup

# a list of fangraphs ids
fg_ids = [826, 5417, 210, 1101]

# find their names and ids from other data sources
data = playerid_reverse_lookup(fg_ids, key_type='fangraphs')
data

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,ramirez,manny,120903,ramim002,ramirma02,210,1993.0,2011.0
1,jeter,derek,116539,jeted001,jeterde01,826,1995.0,2014.0
2,suzuki,ichiro,400085,suzui001,suzukic01,1101,2001.0,2019.0
3,altuve,josé,514888,altuj001,altuvjo01,5417,2011.0,2024.0